### PR TITLE
Bug Fix: Destroy Existing Provider Before Creating New One

### PR DESCRIPTION
**Pull request by ronakkaria**
Fixes the issue of simultaneous updates with 'stopOnTerminate: false'

### CODE REVIEW

**Comment by mauron85** [comment]
Do we really need to destroy provider? Maybe we can just skip start.
```
if (provider != null) {
  return START_REDELIVER_INTENT;
}
```

**Comment by ronakkaria** [comment]
I'm destroying provider just incase a new request to start with a different config has arrived.
We can compare the config object to the old one and selectively destroy the provider or just return START_REDELIVER_INTENT.

**Comment by ronakkaria** [comment]
As for reproducing steps:
Make sure the app you're testing on doesn't store any state about whether a service is running or not.

Basically, every time on start, the app should do two things:
1. Configure the backgroundGelocation with option: "stopOnTerminate: false" (and any other options)
2. onLocationEnabled callback --> backgroundGelocation.start();

No boolean variable in local storage to check if tracking is already running.

Steps to reproduce: Start App, Wait for a location update, See an api call made on server log, Terminate App. Repeat.

You'll see each time the number of api calls made simultaneously increases.

**Comment by mauron85** [comment]
Ok, so basically the same steps as discussed in #88 [comment](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/85#issuecomment-226117742). Will try the fix. I mean can I merge that even before testing as that snippet is safe anyway.

**Comment by ronakkaria** [comment]
Yea.. and like you said, it's maybe not the best thing to do to destroy the provider every time. Destroying the provider loses the location fix the phone has permanently. 

It might be a good idea to destroy only if the config is different the second time around. Else just exit the function.

I'll try and make this change today if I can. Or if you get the time before the Russia match you can do it too :P.

**Comment by mauron85** [comment]
>Yea.. and like you said, it's maybe not the best thing to do to destroy the provider every time. Destroying the provider loses the location fix the phone has permanently.

yes, that was exactly what i had on my mind

**Comment by mauron85** [comment]
i should be saying, whose team will lost that guy should do it. :-D

**Comment by mauron85** [comment]
merged

**Pull request closed without merging**
