### PR TITLE
Remove exports to make types work

### PR DESCRIPTION
**Pull request by jcesarmobile**
Types are not working because of the exports

### CODE REVIEW

**Comment by pserna95** [comment]
This modification gives me an error which says that identifier Event is duplicated

**Comment by mauron85** [comment]
Sorry, but I don't think removing exports is great idea. Maybe it's working workaround for ionic, but it will negatively impact non ionic users. As such I'm not going to merge this.

**Comment by jcesarmobile** [comment]
As you wish, but this is not for Ionic, it's to allow to use the plugin like this `/// <reference types="cordova-plugin-mauron85-background-geolocation" />` https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

If you check the Cordova core plugins, none of them use export on the types and they all work using the triple slash directive. 

Can you provide an example of how do you work with your plugin in Typescript projects?

**Comment by mauron85** [comment]
Correct me if I'm wrong, but Triple-Slash Directive and exports are two different things.

Triple-Slash directive only says where to find type definition. You still need exports, if you don't export anything, such a type definition is useless (and that's the reason it might work for you with ionic -> doesn't check anything).

**Comment by mauron85** [comment]
And btw, my first type definitions were actually without exports. But you can read the issue https://github.com/mauron85/react-native-background-geolocation/issues/311 for why it was changed.

**Comment by jcesarmobile** [comment]
The problem is, for using current types you need to use import in the .ts, and using import is not possible on Cordova projects because you use require keyword in your .js files.
You don't want to change the require to cordova.require and you want to keep current types, so at the moment it's not possible to use your plugin in a Cordova typescript project.

**Comment by mauron85** [comment]
>Can you provide an example of how do you work with your plugin in Typescript projects?

Just did this in 5 min. Should work
https://github.com/mauron85/cordova-typescript

**Comment by jcesarmobile** [comment]
Nice, that way works.
The only problem with this approach is using the plugin with a bundler like webpack, as using import will then look for require keyword in the plugin files, and you have require keyword in the .js files, that causes the linked issue.

Anyway, I'm going to close my PR as it causes the duplicate Event as mentioned by @pserna95

**Comment by mauron85** [comment]
Just installed ionic. And have found two things.

1. `expors` doesn't matter. It's the final line you've removed `export default BackgroundGeolocation;`, which basically means you are ignoring types completely.

2. It will lead to new error as @pserna95 mentioned:

```
ERROR in node_modules/typescript/lib/lib.dom.d.ts(4846,11): error TS2300: Duplicate identifier 'Event'.
node_modules/typescript/lib/lib.dom.d.ts(4905,13): error TS2300: Duplicate identifier 'Event'.
```

**Comment by jcesarmobile** [comment]
No, it's not ignoring the types, they work perfectly fine when using triple slash directive.

As I said, it seems you can do the typings in two different ways, so it can be imported or so it can be used with the triple slash directive.

You are the maintainer and you choose how to do it. I'm fine with you deciding to use import now that I saw your example working, I was not aware of doing it that way, I always used the triple slash directive and triple slash directive is not working with current implementation, that's why I tried to fix it.

Not sure if it's possible to make both work, but my PR broke the import, that's why I closed it.

**Comment by mauron85** [comment]
again. in case of camera plugin, it uses same mechanism to declare used typings https://github.com/apache/cordova-plugin-camera/blob/master/package.json#L5


it works only because you\re not importing module, but rather relying on global var (https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml#L38 and  https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml#L48).

**Comment by jcesarmobile** [comment]
Your plugin also has a global var https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/plugin.xml#L18

But that has nothing to do with it working or not, if I don't add the plugin types with the triple slash directive I can't use the plugins, because that global object is exposed to javascript, but typescript knows nothing about it.

**Pull request closed without merging**
