### PR TITLE
Added option for pauseLocationUpdates (iOS)

### PR DESCRIPTION
**Pull request by GeoTob**
Noticed that iOS location updates stop with the app in background after about 15 minutes.

The new  `pauseLocationUpdates` config flag can be set to `false` to force location updates even if the background app has been automatically paused by iOS.

Addresses #147

### CODE REVIEW

**Comment by mauron85** [comment]
Ok, will merge this. Thanks

**Comment by klidifia** [comment]
I can confirm this resolved #147 - thank you both.

**Comment by anymos** [comment]
Good morning/afternoon,

@GeoTob thank you very much, I was needed this feature as well

@mauron85 , thank you in advance for the merge, do you know already in which release version it s going to be merged ? I have checked the alpha-8 but I did not see it in the code

**Comment by mauron85** [comment]
Merged and published as 2.2.0. Thank you.

**Pull request merged**
