### PR TITLE
Update location message configuration

### PR DESCRIPTION
**Pull request by Oz-at-Work**
Drop NSLocationAlwaysUsageDescription in favour of NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription

I was seeing the following message in the debug window in Xcode

    This app has attempted to access privacy-sensitive data without a usage description. 
    The app's Info.plist must contain both NSLocationAlwaysAndWhenInUseUsageDescription 
    and NSLocationWhenInUseUsageDescription keys with string values explaining to the user 
    how the app uses this data

Switching to `NSLocationWhenInUseUsageDescription` and `NSLocationAlwaysAndWhenInUseUsageDescription` resolves the issue.

### CODE REVIEW

**Comment by vlavrynovych** [comment]
@mauron85 Please review and merge. I hope that it will enable iOS 11 support

**Comment by mauron85** [comment]
Ok. This really seems necessary. @Oz-at-Work @vlavrynovych why can't we also keep `NSLocationAlwaysUsageDescription` for older iOSes?

**Comment by vlavrynovych** [comment]
@mauron85 I've tested it on iOS 11. But in my project I have left the `NSLocationAlwaysUsageDescription` to be sure that I support all the platforms.

@Oz-at-Work, I agree with @mauron85 that we need it. Please update your PR to be safe for previous iOS versions

**Comment by Mehuge** [comment]
Added back support for older platforms

**Pull request merged**
