### PR TITLE
Specify major version of Android Support library

### PR DESCRIPTION
**Pull request by ihadeed**
This fixes build issues when using other plugins that rely on Android Support Library

### CODE REVIEW

**Comment by albe** [comment]
Probably needs to be `23.+` since the plugin targets API level 23 in https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/android/plugin/build.gradle where this also needs to be applied.

Fixes #309

**Comment by mauron85** [comment]
I very reserved to merge PR that change versions of libs. It might resolve your issue, but break for somebody else.

**Comment by mauron85** [comment]
Let's wait when there will be enough people having same issue. Right know only you too seems to be affected. Considering there is close to 5000 downloads a month it doesn't look like common issue.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Any attempt to lock version of dependencies will not be merged.
I know and understand that it will temporarily solve your problem.
But this is not maintainable solution. It might work for some of you, but others may require different versions.

If you need specific version of libraries, then go and fork this project.

**Pull request closed without merging**
