### PR TITLE
Changed authenticator.xml to use mipmap to fix issue #195

### LINKED ISSUE #195: Ionic 2 Android build fails when plugin is added to project
## Your Environment

- Plugin version: 2.2.4
- Platform: Android
- OS version: Linux Mint 18
- Device manufacturer and model: -
- Cordova version (`cordova -v`): 6.4.0
- Cordova platform version (`cordova platform ls`):
  Installed platforms:
  android 6.0.0
  Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  ubuntu ~4.3.4
  webos ~3.7.0
- Plugin configuration options: -
- Link to your project: -

Issue details posted originally here: https://github.com/driftyco/ionic-native/issues/752 and Ionic team says it's this plugin's issue.

When I generate a new starter project:
`ionic start test-project --v2`
and add the [BackgroundGeolocation](http://ionicframework.com/docs/v2/native/backgroundgeolocation/) plugin from Ionic Native:
`ionic plugin add cordova-plugin-mauron85-background-geolocation`
the android build:
`ionic build android`
fails with this error:

```
:processDebugResources
/home/pavlina/Projects/ionic-2.rc-1/platforms/android/res/xml/authenticator.xml:5:19-33: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

/home/pavlina/Projects/ionic-2.rc-1/platforms/android/res/xml/authenticator.xml:6:24-38: AAPT: No resource found that matches the given name (at 'smallIcon' with value '@drawable/icon').

/home/pavlina/Projects/ionic-2.rc-1/platforms/android/build/intermediates/res/merged/debug/xml/authenticator.xml:2: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

/home/pavlina/Projects/ionic-2.rc-1/platforms/android/build/intermediates/res/merged/debug/xml/authenticator.xml:2: error: Error: No resource found that matches the given name (at 'smallIcon' with value '@drawable/icon').

FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.847 secs

Error: /home/pavlina/Projects/ionic-2.rc-1/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/pavlina/Projects/ionic-2.rc-1/platforms/android/res/xml/authenticator.xml:5:19-33: AAPT: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

/home/pavlina/Projects/ionic-2.rc-1/platforms/android/res/xml/authenticator.xml:6:24-38: AAPT: No resource found that matches the given name (at 'smallIcon' with value '@drawable/icon').

/home/pavlina/Projects/ionic-2.rc-1/platforms/android/build/intermediates/res/merged/debug/xml/authenticator.xml:2: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/icon').

/home/pavlina/Projects/ionic-2.rc-1/platforms/android/build/intermediates/res/merged/debug/xml/authenticator.xml:2: error: Error: No resource found that matches the given name (at 'smallIcon' with value '@drawable/icon').

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Please let me know how to fix this, as the plugin is not usable for me at the moment and I need it in my project. 

Thanks!

### PR DESCRIPTION
**Pull request by SPR-JoshLamkin**
this commit fixes #195 by changing authenticator.xml to use mipmap icons in place of drawable

### CODE REVIEW

**Comment by mauron85** [comment]
Ok. I'll merge this. However can you add notice into README.md that this affect cordova version xxx and later. Because for older cordova versions which used drawable this stop working.

**Comment by SPR-JoshLamkin** [comment]
It is not a version of Android whether you put the icons in drawable/ or mipmap/ will work on all versions of Android. mipmap was introduced in Android 4.3 but what matter is that starting with Cordova 6.0.0 they made the default application have icons in the mipmap/ directory. See https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md and look at item  "CB-8722 - Move icons from drawable to mipmap"

**Comment by SPR-JoshLamkin** [comment]
I updated the read me. Thougths?

**Comment by mauron85** [comment]
Nice. Just fix typos:
* Backwards **Compatability**
* update Authenticator.xml to **drawble** directory

and you're done. Sorry for being stickler

**Comment by SPR-JoshLamkin** [comment]
lol. That is what happens when making changes before breakfast. Done and no worries, prefer people to be picky then accept anything.

**Comment by mauron85** [comment]
Merged. Many thanks

**Comment by pdrosos** [comment]
@mauron85 could you please release a version with this fix? Thanks!

**Comment by mauron85** [comment]
just published 2.2.5 to npm

**Pull request merged**
