### PR TITLE
Fix for issue #185

### PR DESCRIPTION
**Pull request by anatoly-khomenko**
Added possibility to specificaly point whether to recalculate
distanceFilter on the go or not.

### CODE REVIEW

**Comment by mauron85** [comment]
Ok. I changed my mind. I will merge this, but before I can do it, we need android impl. as well.

**Comment by klidifia** [comment]
Regarding Android implementation; I believe this issue does not produce on Android and only iOS?
i.e. this only affects iOS.

**Comment by joewoodhouse** [comment]
I agree this needs merging, and isn't relevant to Android. Without this change applied, the plugin is completely unusable on iOS.

**Comment by mauron85** [comment]
Starting 3.0.0 same can be achieved by using RAW_PROVIDER, which is just returning raw locations.

**Pull request closed without merging**
